FROM python:3.9-slim

# Defina o diretório de trabalho
WORKDIR /app

# Copie o script Python para o container
COPY carguru.py .

# Execute o script Python quando o container iniciar
CMD ["python", "carguru.py"]
